AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS CFN Custom Resources

Parameters:
  TargetOuIds:
    Type: String
    Description: Comma separated list of OUs
  TargetRegions:
    Type: String
    Description: Comma separated list of regions
  AwsOrganizationId:
    Type: String
    Description: AWS Organization ID
  CiCdOuIds:
    Type: String
    Description: Comma separated listist of CI/CD OUs
  CicdAwsAccountId:
    Type: String
    Description: AWS Account ID of the CI/CD account
  DnsRootZoneId:
    Type: String
    Description: DNS Root Zone ID
  DnsRootZoneAccountId:
    Type: String
    Description: DNS Root Zone Account ID
  ManageDnsZoneIamRole:
    Type: String
    Description: IAM role name for RegisterDnsZone

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - I3011

Resources:
  BuildAccountStackSet:
    Type: AWS::Serverless::Application
    Properties:
      Location: './stacksets/build-account/stackset.yaml'
      Parameters:
        TargetOuIds: !Ref CiCdOuIds
        TargetRegions: !Ref TargetRegions
        AwsOrganizationId: !Ref AwsOrganizationId
        CustomResourceTopicName: CfnCustomResource
        DnsRootZoneId: !Ref DnsRootZoneId
        DnsRootZoneAccountId: !Ref DnsRootZoneAccountId
        ManageDnsZoneIamRole: !Ref ManageDnsZoneIamRole

  DeployAccountStackSet:
    Type: AWS::Serverless::Application
    Properties:
      Location: './stacksets/deploy-account/stackset.yaml'
      Parameters:
        TargetOuIds: !Ref TargetOuIds
        TargetRegions: !Ref TargetRegions
        CustomResourceSsmParamName: /org/cicd/CustomResourceTopic
        CustomResourceArn: !Sub arn:aws:sns:${AWS::Region}:${CicdAwsAccountId}:CfnCustomResource
