AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS CFN Custom Resources

Parameters:
  TargetOuIds:
    Type: String
    Description: Comma separated list of OUs
  TargetRegions:
    Type: String
    Description: Comma separated list of regions
  AwsOrganizationId:
    Type: String
    Description: AWS Organization ID
  CiCdOuIds:
    Type: String
    Description: Comma separated listist of CI/CD OUs
  CicdAwsAccountId:
    Type: String
    Description: AWS Account ID of the CI/CD account

Resources:
  StacksetTemplateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-stacksets-${AWS::AccountId}-${AWS::Region}"

  BuildAccountStackSet:
    Type: AWS::Serverless::Application
    Properties:
      Location: './stacksets/build-account/stackset.yaml'
      Parameters:
        StacksetTemplateBucket: !Ref StacksetTemplateBucket
        TargetOuIds: !Ref CiCdOuIds
        TargetRegions: !Ref TargetRegions
        AwsOrganizationId: !Ref AwsOrganizationId
        CustomResourceTopicName: CfnCustomResourceTopicName

  DeployAccountStackSet:
    Type: AWS::Serverless::Application
    Properties:
      Location: './stacksets/deploy-account/stackset.yaml'
      Parameters:
        StacksetTemplateBucket: !Ref StacksetTemplateBucket
        TargetOuIds: !Ref TargetOuIds
        TargetRegions: !Ref TargetRegions
        CustomResourceSsmParamName: /org/cicd/CustomResourceTopic
        CustomResourceArn: !Sub aws:arn:sns:${AWS::Region}:${CicdAwsAccountId}:CfnCustomResourceTopicName

  DeployAccountManagementStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: './stacksets/deploy-account/template.yaml'
      Parameters:
        CustomResourceSsmParamName: /org/cicd/CustomResourceTopic
        CustomResourceArn: !Sub aws:arn:sns:${AWS::Region}:${CicdAwsAccountId}:CfnCustomResourceTopicName
