AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS CFN Custom Resources

Parameters:
  AwsOrganizationId:
    Type: String
    Description: AWS Organization ID
  CicdAwsAccountId:
    Type: String
    Description: AWS Account ID of the CI/CD account
  ManageDnsZoneIamRole:
    Type: String
    Description: IAM role name
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - I3011

Resources:
  DeployAccountManagementStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: './stacksets/deploy-account/template.yaml'
      Parameters:
        CustomResourceSsmParamName: /org/cicd/CustomResourceTopic
        CustomResourceArn: !Sub arn:aws:sns:${AWS::Region}:${CicdAwsAccountId}:CfnCustomResource

  DnsManagementStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: './stacksets/dns-mgmt/template.yaml'
      Parameters:
        AwsOrganizationId: !Ref AwsOrganizationId
        ManageDnsZoneIamRole: !Ref ManageDnsZoneIamRole
