AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS CFN Custom Resources

Parameters:
  CicdAwsAccountId:
    Type: String
    Description: AWS Account ID of the CI/CD account

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - I3011

Resources:
  DeployAccountManagementStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: './stacksets/deploy-account/template.yaml'
      Parameters:
        CustomResourceSsmParamName: /org/cicd/CustomResourceTopic
        CustomResourceArn: !Sub arn:aws:sns:${AWS::Region}:${CicdAwsAccountId}:CfnCustomResource
