Metadata:
  localTemplateFile: &template_body ./template.yaml

AWSTemplateFormatVersion: '2010-09-09'
Description: Execution account CFN Custom Resources StackSet

Parameters:
  TargetOuIds:
    Type: CommaDelimitedList
    Description: Comma separated list of OUs
  TargetRegions:
    Type: CommaDelimitedList
    Description: Comma separated list of regions
  AwsOrganizationId:
    Type: String
    Description: AWS Organization ID
  CustomResourceTopicName:
    Type: String
    Description: Name of the SNS topic for custom resources
  DnsRootZoneId:
    Type: String
    Description: Hosted Zone ID
  DnsRootZoneAccountId:
    Type: String
    Description: DNS Root Zone Account ID

Resources:
  DeployAccountCfnCustomResourcesSupportStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: OrgBuildAccountCfnCustomResources
      Description: Provides shared AWS CFN Custom Resources
      CallAs: DELEGATED_ADMIN
      Parameters:
        - ParameterKey: AwsOrganizationId
          ParameterValue: !Ref AwsOrganizationId
        - ParameterKey: CustomResourceTopicName
          ParameterValue: !Ref CustomResourceTopicName
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref TargetOuIds
          Regions: !Ref TargetRegions
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
      TemplateBody: *template_body
