AWSTemplateFormatVersion: '2010-09-09'
Description: Build account CFN Custom Resources StackSet

Parameters:
  TargetOuIds:
    Type: CommaDelimitedList
    Description: Comma separated list of OUs
  TargetRegions:
    Type: CommaDelimitedList
    Description: Comma separated list of regions
  StacksetTemplateBucket:
    Type: String
    Description: S3 bucket for stackset templates
  AwsOrganizationId:
    Type: String
    Description: AWS Organization ID
  CustomResourceTopicName:
    Type: String
    Description: Name of the SNS topic for custom resources

Resources:
  DeployAccountCfnCustomResourcesSupportStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      TemplateURL: !Sub https://${StacksetTemplateBucket}.s3.amazonaws.com/build-account/template.yaml
      StackSetName: OrgBuildAccountCfnCustomResources
      Description: Provides shared AWS CFN Custom Resources
      Parameters:
        - ParameterKey: AwsOrganizationId
          ParameterValue: !Ref AwsOrganizationId
        - ParameterKey: CustomResourceTopicName
          ParameterValue: !Ref CustomResourceTopicName
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref TargetOuIds
          Regions: !Ref TargetRegions
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      PermissionModel: SERVICE_MANAGED
