Metadata:
  localTemplateFile: &template_body ./translated-template.json

AWSTemplateFormatVersion: '2010-09-09'
Description: Execution account CFN Custom Resources StackSet

Parameters:
  TargetOuIds:
    Type: CommaDelimitedList
    Description: Comma separated list of OUs
  TargetRegions:
    Type: CommaDelimitedList
    Description: Comma separated list of regions
  AwsOrganizationId:
    Type: String
    Description: AWS Organization ID
  CustomResourceTopicName:
    Type: String
    Description: Name of the SNS topic for custom resources
  DnsRootZoneId:
    Type: String
    Description: Hosted Zone ID
  DnsRootZoneAccountId:
    Type: String
    Description: DNS Root Zone Account ID
  ManageDnsZoneIamRole:
    Type: String
    Description: IAM role name for RegisterDnsZone

Resources:
  DeployAccountCfnCustomResourcesSupportStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: OrgBuildAccountCfnCustomResources
      Description: Provides shared AWS CFN Custom Resources
      CallAs: DELEGATED_ADMIN
      Parameters:
        - ParameterKey: AwsOrganizationId
          ParameterValue: !Ref AwsOrganizationId
        - ParameterKey: CustomResourceTopicName
          ParameterValue: !Ref CustomResourceTopicName
        - ParameterKey: DnsRootZoneId
          ParameterValue: !Ref DnsRootZoneId
        - ParameterKey: DnsRootZoneAccountId
          ParameterValue: !Ref DnsRootZoneAccountId
        - ParameterKey: ManageDnsZoneIamRole
          ParameterValue: !Ref ManageDnsZoneIamRole
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref TargetOuIds
          Regions: !Ref TargetRegions
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      ManagedExecution:
        Active: true
      OperationPreferences:
        RegionConcurrencyType: PARALLEL
        FailureToleranceCount: 1
        MaxConcurrentCount: 5
      Capabilities:
        - CAPABILITY_NAMED_IAM
      PermissionModel: SERVICE_MANAGED
      TemplateBody: *template_body

