AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CFN Custom Resources Support

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - I3011

Parameters:
  AwsOrganizationId:
    Type: String
    Description: AWS Organization ID
  CustomResourceTopicName:
    Type: String
    Description: Name of the SNS topic for custom resources
  DnsRootZoneId:
    Type: String
    Description: Hosted Zone ID
  DnsRootZoneAccountId:
    Type: String
    Description: DNS Root Zone Account ID
  SarTemplateUrl:
    Type: String
    Description: SAR template URL

Resources:
  CfnCustomResourcesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref SarTemplateUrl
      Parameters:
        AwsOrganizationId: !Ref AwsOrganizationId
        CustomResourceTopicName: !Ref CustomResourceTopicName
        DnsRootZoneId: !Ref DnsRootZoneId
        DnsRootZoneAccountId: !Ref DnsRootZoneAccountId