AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CFN Custom Resources Support

Parameters:
  AwsOrganizationId:
    Type: String
    Description: AWS Organization ID

Resources:
  CustomResourceTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: CFN Custom Resource Topic

  CustomResourceTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sns:Publish
            Resource: !Ref CustomResourceTopic
            Condition:
              StringEquals:
                "aws:PrincipalOrgID":
                  - !Ref AwsOrganizationId
      Topics:
        - !Ref CustomResourceTopic

Outputs:
  CustomResourceTopicArn:
    Value: !Ref CustomResourceTopic
    Export:
      Name: CustomResourceTopicArn