AWSTemplateFormatVersion: '2010-09-09'
Description: DNS zone management

Parameters:
  AwsOrganizationId:
    Type: String
    Description: AWS Organization ID
  ManageDnsZoneIamRole:
    Type: String
    Description: IAM role name

Resources:
  ManageDnsZoneIamrole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ManageDnsZoneIamRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceOrgID: !Ref AwsOrganizationId
      Policies:
        - PolicyName: ModifyZoneRecords
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - route53:ChangeResourceRecordSets
                Resource: '*'